### ISSUE TITLE
Drop "result_2" from cwr result output

### ISSUE THREAD

**Issue by arosales** [juju-solutions/cloud-weather-report#19]
Currently when running CWR two html pages will be generated:

<bundle-name>-<date:time>-result.html
<bundle-name>-<date:time>-result_2.html

Per conversations the html report we want to keep is "result.html," thus this bug is to drop "result_2.html" and any resources associated with it so users are not confused as to which report to view.

-thanks,
Antonio

**Comment by seman** [comment]
Resolved by https://github.com/juju-solutions/cloud-weather-report/pull/47
