### ISSUE TITLE
Group and label tests by suite

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/cloud-weather-report#48]
Bundletester runs multiple "test suites" for a bundle, where each suite is either all of the tests for a given charm or the set of tests for the bundle itself.  The test results page doesn't indicate in any way which suites (and thus which charms) each result goes with, which makes telling exactly what failed difficult.

For example, the following `results.json` snippet contains `charm proof` and `00-setup` results for both `cs:trusty/ganglia-2` and `cs:trusty/hadoop-namenode-3`:

```json
"tests": [
  {
    "duration": "0.70",
    "output": "...",
    "suite": "cs:trusty/ganglia-2",
    "name": "charm-proof",
    "result": "PASS"
  },
  {
    "duration": "0.00",
    "output": "...",
    "suite": "cs:trusty/ganglia-2",
    "name": "00-setup",
    "result": "PASS"
  },
  {
    "duration": "0.69",
    "output": "",
    "suite": "cs:trusty/hadoop-namenode-3",
    "name": "charm-proof",
    "result": "PASS"
  },
  {
    "duration": "0.00",
    "output": "...",
    "suite": "cs:trusty/hadoop-namenode-3",
    "name": "00-setup",
    "result": "PASS"
  },
]
```

Without any labels, it can be hard to differentiate results:
![cwr-without-labels](https://cloud.githubusercontent.com/assets/406082/15912818/8fc14d02-2da4-11e6-82d6-0cd5e74d5bfc.png)

Adding some sort of headers to separate them makes it much clearer.  Something along the lines of:
![cwr-with-labels](https://cloud.githubusercontent.com/assets/406082/15912830/a0d7a816-2da4-11e6-98ce-e78d3bebaad2.png)

**Comment by seman** [comment]
Resolved by https://github.com/juju-solutions/cwr-status/pull/17/
