### ISSUE TITLE
Incorrectly showing AWS failure as timeout error

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/cloud-weather-report#53]
Note the AWS results for `02-scale-standalone.py` in this run:

http://status.juju.solutions/bundle/cwr-test-389

```
"11":
    agent-state: error
    agent-state-info: 'cannot run instances: Your quota allows for 0 more running
      instance(s). You requested at least 1 (InstanceLimitExceeded)'
    instance-id: pending
    series: trusty

...

File "/usr/lib/python3/dist-packages/amulet/helpers.py", line 117, in signal_handler
    raise TimeoutError()
amulet.helpers.TimeoutError
```

I think this goes back to an earlier discussion where we should analyze the juju status output for all failures... If any machines are error or pending, we consider that a provisioning failure (yellow triangle).

**Comment by seman** [comment]
Resolved by #83
