### ISSUE TITLE
Need to have a --no-browser option for automated runs

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/cloud-weather-report#57]
Otherwise cwr will bail if no browser is installed

**Comment by secroft** [comment]
When executing cwr, there should be an option of --no-browser, thus just producing the results, or remove the automatic ouput to a browser and if someone wants to use links or something similar, then they add a flag --browser. It's annoying to see the output when links or an equivalent isn't installed

**Comment by seman** [comment]
Resolved by #68.  By default, the result is not opened in the browser.
