### ISSUE TITLE
Add a column for bundle name

### ISSUE THREAD

**Issue by seman** [juju-solutions/cloud-weather-report#78]
Currently, there are `Bundle` `Date`, `Latest Test Results` columns. I think this should be changed to `Bundle`, `Bundle Location`, `Date`, `Latest Test Results` columns.  

It make sense to sort by bundle names rather than locations. This also allows us to add custom label to the bundles, example bundles run on multiple MAAS machines can be labeled differently.

**Comment by johnsca** [comment]
I'm not ashtray against this, but I don't understand the bit about "multiple MAAS machines."  Wouldn't that just be more providers?

**Comment by seman** [comment]
Resolved #88
