### ISSUE TITLE
cwr + bundletester + amulet fill up disk

### ISSUE THREAD

**Issue by sinzui** [juju-solutions/cloud-weather-report#79]
A machine we cwr continuously on has filled of its disk twice in 5 days. 7.5GB is tmp files were lfet behind. cwr + bundletester + amulet need to guarantee cleanup. I am picking on cwr because it is the tool I am running.

Assuming that bundletester + amulet will leak, cwr, could isolate where tmp files are created, and ensure the location is removed on exit. The calls to start bundletester could be wrapped in something like this

```
@contextmanager
def temp_dir(parent=None, keep=False):
    directory = mkdtemp(dir=parent)
    try:
        yield directory
    finally:
        if not keep:
            rmtree(directory)

with temp_dir() as tmpdir
    os.environ['TMPDIR'] = tmpdir
    call_bundle_tester()
```

**Comment by nskaggs** [comment]
I would further that these tools need a test runner than guarantees test isolation and cleanup, as well as reproducibility (to the extent possible barring external services). As it stands running these on your machine modifies it and exposes your host to the whims of what is under test.

**Comment by tvansteenburgh** [comment]
It's possible that bundletester leaves a temp dir behind - I'll take a look. I think amulet is pretty clean but I'll double-check that too. If this happens again it would be helpful to see the composition of those 7.5GB tmp files before they are deleted.

Regarding isolation - on the charm-bundle-slave we run bundletester inside a container for this very reason.

**Comment by nskaggs** [comment]
@tvansteenburgh thanks for the clarification on how you run it. I was assuming the intent was to run in a container -- is this something bundletester can help make easy to do? I'm just curious how someone might run it locally themselves for instance.

**Comment by tvansteenburgh** [comment]
I just released bundletester-0.9.2, which cleans up after itself. I think there is something else causing the disk to fill though. One run of bundletester left a single temp dir of only 28K.

**Comment by tvansteenburgh** [comment]
@nskaggs Here's an example of running bundletester in a docker container:

```bash
#!/bin/bash
JUJU_HOME=$HOME/.local/share/juju

# :devel tag for juju 2, :latest for juju 1
# If you use juju 1 you'll want to bind-mount
# ~/.juju instead of ~/.local/share/juju
CHARMBOX=jujusolutions/charmbox:devel

ARGS="$@"

sudo docker run --rm \
      -u ubuntu \
      -v ${JUJU_HOME}:/home/ubuntu/.local/share/juju \
      -t $CHARMBOX \
      sudo bundletester -Fvl DEBUG $ARGS
```

**Comment by seman** [comment]
@tvansteenburgh thanks for releasing a new bundlertester. It was leaving `bundletester-*` dir in /tmp but the size was small. I also see `amulet_deployment_*` and `amulet-juju-deployer-*` dir in /tmp.

@nskaggs https://github.com/juju-solutions/build-cloud is a test runner for this. It used to run cwr in docker container but no charmbox image for PPC and failed creating one so switched back to using the host for testing. We can update build-cloud to use lxd.

**Comment by johnsca** [comment]
Removing the Docker container without a replacement opens us up to many environmental issues and cross-test contamination.  I don't understand why this was done unilaterally and across the board just because it didn't work on one platform.

It is imperative that we restore the isolation as soon as possible.  I'm fine with using lxd instead of Docker, but that seems like more work than resolving the issue with charmbox on Power.  As far as I know, Docker should work on Power.  I don't see an issue on https://github.com/juju-solutions/charmbox/issues for PPC; can you please open one with all of the info you have on the failure?
