### ISSUE TITLE
PyYAML Conflict

### ISSUE THREAD

**Issue by petevg** [juju-solutions/cloud-weather-report#91]
There is a PyYAML version conflict in cloud weather report's dependencies.

cloud-weather-report requires PyYAML >= 3.11

jujubundlelib required PyYAML==3.11

Due to the way that pip works, pip will currently install PyYAML 3.12, due to the `PyYAML>=3.11` line in cloud-weather-report's requirements, then become sad when it comes time to install jujubundlelib and fail.

We need to either pin PyYAML to 3.11 in this package, or tweak jujudbundlelib to require >= 3.11

**Comment by kwmonroe** [comment]
fixed in #92
